name: Code Formatter
on:
    workflow_dispatch:
    push:
        paths:
            - "**/*.js"
            - "**/*.ts"
            - "**/*.md"
            - "**/*.json"
            - "!.github/**"

jobs:
    format:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ vars.BUN_VERSION }}

            - name: Install Dependencies
              run: bun install --ignore-scripts

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}

            - name: Run Prettier
              run: bun run prettier

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "chore(prettier): code formatting"
                  skip_checkout: true
