name: Update Content
on:
    workflow_dispatch:
    push:
        paths:
            - "script/**"
            - "**/*.c"
            - "**/*.py"
            - "**/*.fprg"
            - "**/*.ps1"
            - "**/*.sql"
            - "**/*.php"
            - "**/*.html"
            - "**/*.js"
            - "**/*.ts"
            - "**/*.java"
            - "**/*.ino"

jobs:
    update:
        name: Update Content
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ vars.BUN_VERSION }}

            - name: Install Dependencies
              run: bun install --production --ignore-scripts

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}

            - name: Run Script
              run: bun generator:docs

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "chore(script): update content"
                  skip_checkout: true
