name: Update Content
on:
    workflow_dispatch:
    push:
        paths:
            - "script/**"
            - "**/*.fprg"
            - "**/*.c"

jobs:
    update:
        name: Update Content
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: 8.7.5
                  run_install: |
                      args: [--ignore-scripts]

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: pnpm

            - name: Run Script
              run: pnpm script:run

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "chore(script): update content"
                  skip_checkout: true
