name: Update
on:
    workflow_dispatch:
    push:

jobs:
    update:
        name: Update Content
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  run_install: false
                  version: 8

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: pnpm

            - name: Install Dependencies
              run: pnpm install --ignore-scripts

            - name: Run Script
              run: pnpm script:run

            - name: Automatically Commit Changed
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  push_options: "--force"
                  commit_options: "--no-verify"
                  commit_message: "chore(script): update content"
                  skip_checkout: true
